---
title: "car carbon emissions"
author: "Shuhan Song"
date: "1/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data Source: [Fuel Economy](https://www.fueleconomy.gov/feg/download.shtml)

```{r}
library(tidyverse)
```

```{r}
vehicles <- read_csv("vehicles.csv")


```

```{r}
skimr::skim(vehicles)
unique(vehicles$fuelType)
count(vehicles, fuelType)
```

```{r}
vehicles_fuelType <- vehicles %>% 
  select(fuelType, fuelType1, fuelType2) %>% 
  filter(fuelType == "Gasoline or E85") 
count(vehicles, fuelType, fuelType1, fuelType2)
```

```{r}
count(vehicles, fuelType2)

filter(vehicles, UCityA == 0) %>% 
  select(fuelType, fuelType1, fuelType2, UCity:UHighwayA) %>% 
  count(fuelType)

filter(vehicles, fuelType == "Gasoline or natural gas") %>% 
  select(fuelType, fuelType1, fuelType2, UCity:UHighwayA)

filter(vehicles, fuelType == "Gasoline or propane") %>% 
  select(fuelType, fuelType1, fuelType2, UCity:UHighwayA)

filter(vehicles, fuelType == "Gasoline or E85") %>% 
  select(fuelType, fuelType1, fuelType2, UCity:UHighwayA)

filter(vehicles, fuelType == "Regular Gas or Electricity") %>% 
  select(fuelType, fuelType1, fuelType2, UCity:UHighwayA)
```


```{r}
hybrid_car <- vehicles %>% 
  filter(fuelType %in% c("Premium and Electricity", "Premium Gas or Electricity", "Regular Gas and Electricity", "Regular Gas or Electricity")) %>% 
  select(UCity:UHighwayA) %>% 
  mutate(car_type = "Hybrid car",
         city_mpg = (UCity+UCityA)/2,
         highway_mpg = (UHighway+UHighwayA)/2)

electric_car <- vehicles %>% 
  filter(fuelType %in% c("Electricity")) %>% 
  select(UCity:UHighwayA) %>% 
  mutate(car_type = "Electric car",
         city_mpg = UCity,
         highway_mpg = UHighway)

fuel_car <- vehicles %>% 
  filter(fuelType %in% c("Midgrade", "Premium", "Regular")) %>% 
  select(UCity:UHighwayA) %>% 
  mutate(car_type = "Gasoline car",
         city_mpg = UCity,
         highway_mpg = UHighway)

car_mpg <- rbind(hybrid_car, electric_car, fuel_car) %>% 
  mutate(avg_mpg = (city_mpg + highway_mpg)/2) %>% 
  group_by(car_type) %>% 
  summarize(avg_highway = mean(highway_mpg),
            avg_city = mean(city_mpg),
            avg_both = mean(avg_mpg))


car_GramPerMile <- car_mpg %>% 
  mutate(carbon_GramPerGallon = 8900) %>% 
  mutate(highway = carbon_GramPerGallon/avg_highway,
         city = carbon_GramPerGallon/avg_city,
         both = carbon_GramPerGallon/avg_both)

non_car_GramPerMile <- data.frame(trans_type = c("Walk", "Bike", "Bus"),
                                  carbon_burden = c(10, 16, 8900/163.1))

transport_gram_per_mile <- car_GramPerMile %>% 
  select(car_type, both) %>% 
  rename(trans_type = car_type,
         carbon_burden = both) %>% 
  rbind(non_car_GramPerMile)

transport_gram_per_mile <- rbind(data.frame(trans_type = "No transportation", carbon_burden = 0),
                                 transport_gram_per_mile)
  

write_csv(transport_gram_per_mile, "transport_gram_per_mile.csv")
```

